---
title: "Compare the batch effect between seqFISH and scRNA-seq"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---

# Load dependencies and source data

```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
library(igraph)
library(reshape2)
library(knitr)
library(Rtsne)
library(scater)
library(irlba)
library(scales)
library(biomaRt)
library(cowplot)
library(batchelor)
ncores = 1
#mcparam = MulticoreParam(workers = ncores)
#register(mcparam)

#root.dir = "/Users/alsu/Develop/spatial/mouse_embryo/"
root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/visualization_functions.R"))
# load sce files with counts data; clean from cells with 0 area and total # mRNA < user's threshold 
load_embryo_8.5(threshTotalRNA = 0, filterNullArea = T, filterBigClumps = T, dir = "cluster")

# work only with the embryo_1 for now
idx = meta$embryo == "embryo_1"
meta = meta[idx,]
sce = sce[,idx]

# discard Xist 
idx = setdiff(1:dim(sce)[1], which(rownames(sce) %in% c("Xist")) )
sce = sce[idx,]
  
#source("/Users/alsu/Develop/FetalAlcoholSyndrome/FetalAlcoholSyndromeScripts/core_functions_local.R")
# load scRNA-seq atlas
load_data_atlas(rownames_ensembl = F)

sce.atlas = scater::normalize(sce.atlas)
meta.atlas$celltype[meta.atlas$doublet] = "Doublet"
meta.atlas$celltype[meta.atlas$stripped] = "Stripped"
# discard doublets and stripped for the atlas - we don't want to map to them
idx = !meta.atlas$celltype %in% c("Doublet", "Stripped")
meta.atlas = meta.atlas[idx,]
sce.atlas = sce.atlas[,idx]

# keep only those genes that are in seqFISH (excluding Xist and Cavin3)
idx = rownames(sce.atlas) %in% rownames(sce)
sce.atlas = sce.atlas[idx,]

# get the same order of rows for sce and sce.atlas
sce = sce[order(rownames(sce)),]
sce.atlas = sce.atlas[order(rownames(sce.atlas)),]

# join
counts.seq = as.matrix( assay( sce, "logcounts.area" ))
counts.atlas = as.matrix( logcounts( sce.atlas ) )
counts.joint = cbind(counts.atlas , counts.seq )

# join z-counts
z.counts.seq = apply(counts.seq, 1, function(x){
  out = scale(x)
  out[is.na(out)] <- 0
  return(out)
})
z.counts.seq = t(z.counts.seq)
z.counts.seq = z.counts.seq[order(rownames(z.counts.seq)),]

z.counts.atlas = apply(counts.atlas, 1, function(x){
  out = scale(x)
  out[is.na(out)] <- 0
  return(out)
})
z.counts.atlas = t(z.counts.atlas)
z.counts.atlas = z.counts.atlas[order(rownames(z.counts.atlas)),]

z.counts.joint = cbind(z.counts.atlas , z.counts.seq )

# get pca
nPC = 100
counts.joint.pca = prcomp_irlba(t(counts.joint), n = nPC)$x
counts.atlas.pca = counts.joint.pca[1:ncol(sce.atlas),]
counts.seq.pca = counts.joint.pca[-(1:ncol(sce.atlas)),]
z.counts.joint.pca = prcomp_irlba(t(z.counts.joint), n = nPC)$x
z.counts.atlas.pca = z.counts.joint.pca[1:ncol(sce.atlas),]
z.counts.seq.pca = z.counts.joint.pca[-(1:ncol(sce.atlas)),]

sample.type = c(meta.atlas$stage, meta$embryo)

# get colors for sample.type
sample.type_colours = c("E6.5" = "#D53E4F",
                  "E6.75" = "#F46D43",
                  "E7.0" = "#FDAE61",
                  "E7.25" = "#FEE08B",
                  "E7.5" = "#FFFFBF",
                  "E7.75" = "#E6F598",
                  "E8.0" = "#ABDDA4",
                  "E8.25" = "#66C2A5",
                  "E8.5" = "#3288BD",
                  "mixed_gastrulation" = "#A9A9A9", "embryo_1" = "black")

```

# T-SNE - raw: on 350 seqFISH genes (drop Xist)

## Uncorrected atlas + seqFISH

```{r uncorr-atlas-seq}

current.tsne = Rtsne(counts.joint.pca, pca = F, check_duplicates = FALSE)$Y
current.tsne = as.data.frame(current.tsne)
current.tsne = cbind(current.tsne, sample.type)
  
ggplot(current.tsne, aes(x = V1, y = V2, col = factor(sample.type) )) +
  geom_point(size = 0.5) + 
  scale_colour_manual(values = sample.type_colours, name = "") +
  theme(legend.position = "bottom", axis.line = element_blank(),
        axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank()) 

```

## Corrected (atlas) + seqFISH

```{r corr-atlas-seq}

unq.samples = unique(meta.atlas$sample)
counts.atlas.pca.bySamples = lapply(unq.samples, function(x){
  counts.atlas.pca[meta.atlas$sample == x, ]
})
# call batch correction for atlas samples
atlas.corrected.pca = do.call(reducedMNN, c(counts.atlas.pca.bySamples))
atlas.corrected.pca = atlas.corrected.pca$corrected

# join with seq and perform tSNE
current.pca = rbind(atlas.corrected.pca, counts.seq.pca)

current.tsne = Rtsne(current.pca, pca = F, check_duplicates = FALSE)$Y
current.tsne = as.data.frame(current.tsne)
current.tsne = cbind(current.tsne, sample.type)
  
ggplot(current.tsne, aes(x = V1, y = V2, col = factor(sample.type) )) +
  geom_point(size = 0.5) + 
  scale_colour_manual(values = sample.type_colours, name = "") +
  theme(legend.position = "bottom", axis.line = element_blank(),
        axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank()) 

```

## Corrected(corrected(atlas) + seqFISH)

```{r corr-corr-atlas-seq}

unq.samples = unique(meta.atlas$sample)
counts.atlas.pca.bySamples = lapply(unq.samples, function(x){
  counts.atlas.pca[meta.atlas$sample == x, ]
})
# call batch correction for atlas samples
atlas.corrected.pca = do.call(reducedMNN, c(counts.atlas.pca.bySamples ))
atlas.corrected.pca = atlas.corrected.pca$corrected
# correction for corrected atlas + seq
corrected.atlas.corrected.pca = reducedMNN(atlas.corrected.pca, counts.seq.pca)
corrected.atlas.corrected.pca = corrected.atlas.corrected.pca$corrected

current.tsne = Rtsne(corrected.atlas.corrected.pca, pca = F, check_duplicates = FALSE)$Y
current.tsne = as.data.frame(current.tsne)
current.tsne = cbind(current.tsne, sample.type)
  
ggplot(current.tsne, aes(x = V1, y = V2, col = factor(sample.type) )) +
  geom_point(size = 0.5) + 
  scale_colour_manual(values = sample.type_colours, name = "") +
  theme(legend.position = "bottom", axis.line = element_blank(),
        axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank()) 

```


# T-SNE - z-score: on 350 seqFISH genes (drop Xist)

## Uncorrected atlas + seqFISH

```{r z-uncorr-atlas-seq}

current.tsne = Rtsne(z.counts.joint.pca, pca = F, check_duplicates = FALSE)$Y
current.tsne = as.data.frame(current.tsne)
current.tsne = cbind(current.tsne, sample.type)
  
ggplot(current.tsne, aes(x = V1, y = V2, col = factor(sample.type) )) +
  geom_point(size = 0.5) + 
  scale_colour_manual(values = sample.type_colours, name = "") +
  theme(legend.position = "none", axis.line = element_blank(),
        axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank()) 

```

## Corrected (atlas) + seqFISH

```{r z-corr-atlas-seq}

unq.samples = unique(meta.atlas$sample)
counts.atlas.pca.bySamples = lapply(unq.samples, function(x){
  z.counts.atlas.pca[meta.atlas$sample == x, ]
})
# call batch correction for atlas samples
atlas.corrected.pca = do.call(reducedMNN, c(counts.atlas.pca.bySamples))
atlas.corrected.pca = atlas.corrected.pca$corrected

# join with seq and perform tSNE
current.pca = rbind(atlas.corrected.pca, z.counts.seq.pca)

current.tsne = Rtsne(current.pca, pca = F, check_duplicates = FALSE)$Y
current.tsne = as.data.frame(current.tsne)
current.tsne = cbind(current.tsne, sample.type)
  
ggplot(current.tsne, aes(x = V1, y = V2, col = factor(sample.type) )) +
  geom_point(size = 0.5) + 
  scale_colour_manual(values = sample.type_colours, name = "") +
  theme(legend.position = "none", axis.line = element_blank(),
        axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank()) 

```

## Corrected(corrected(atlas) + seqFISH)

```{r z-corr-corr-atlas-seq}

unq.samples = unique(meta.atlas$sample)
counts.atlas.pca.bySamples = lapply(unq.samples, function(x){
  z.counts.atlas.pca[meta.atlas$sample == x, ]
})
# call batch correction for atlas samples
atlas.corrected.pca = do.call(reducedMNN, c(counts.atlas.pca.bySamples ))
atlas.corrected.pca = atlas.corrected.pca$corrected
# correction for corrected atlas + seq
corrected.atlas.corrected.pca = reducedMNN(atlas.corrected.pca, z.counts.seq.pca)
corrected.atlas.corrected.pca = corrected.atlas.corrected.pca$corrected

current.tsne = Rtsne(corrected.atlas.corrected.pca, pca = F, check_duplicates = FALSE)$Y
current.tsne = as.data.frame(current.tsne)
current.tsne = cbind(current.tsne, sample.type)
  
ggplot(current.tsne, aes(x = V1, y = V2, col = factor(sample.type) )) +
  geom_point(size = 0.5) + 
  scale_colour_manual(values = sample.type_colours, name = "") +
  theme(legend.position = "bottom", axis.line = element_blank(),
        axis.text = element_blank(), axis.ticks = element_blank(), axis.title = element_blank()) 

```



#Session Info
```{r sessinf}
sessionInfo()
```
