---
title: "Pipleine to assess which atlas batch or samples to use for imputation."
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---


# Load dependencies and source data

```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(Rtsne)
library(ggplot2)
library(batchelor)
library(BiocParallel)
library(irlba)
library(cowplot)
library(ggplot2)
library(ggpubr)
library(umap)

set.seed(32)

root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
#root.dir = "/Users/alsu/Develop/spatial/mouse_embryo/"
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/visualization_functions.R"))

# load seq
load_embryo_8.5(dir = "cluster")
sce.seq = sce[!rownames(sce) == "Xist",]

# load atlas
sce.atlas = readRDS(paste0(root.dir, "data/reducedAtlas/E8_25__E8_5.rds"))
meta.atlas = data.frame( colData(sce.atlas) )
counts.atlas = logcounts(sce.atlas)
hvgs = getHVGs(sce.atlas, min.mean = 1e-3)

# batch factor
sce.cosine = assay(sce.atlas, "cosineNorm")
batchFactor = factor(c(as.character(sce.atlas$sample)))


```

# Stat

```{r atlas-stat, warning=FALSE}

tab = as.data.frame( table(meta.atlas$sample, meta.atlas$sequencing.batch) )
colnames(tab) = c("sample", "sequencing.batch", "n.cells")
tab = merge(tab, data.frame( unique( meta.atlas[, c("sample", "stage")]) ), all.x = T, all.y = F)
tab = tab[tab$n.cells > 0,]
print(tab)


```

# Batch effect

## HVGS (atlas)

```{r batch-effect-hvgs, fig.cap="Batch effect: HVGs.", fig.height=10, fig.wide=TRUE, warning=FALSE}

# calc PCs
mbpca.hvgs = multiBatchPCA(sce.cosine[rownames(sce.cosine) %in% hvgs,], batch = batchFactor, d = 50)
# batch correct
out = do.call(reducedMNN, mbpca.hvgs)
corrected.hvgs = out$corrected

# get UMAP coords
mbpca.hvgs = do.call(rbind, mbpca.hvgs)
uncorrected.hvgs.umap = umap(mbpca.hvgs, min_dist = 0.7)
uncorrected.hvgs.umap = as.data.frame( uncorrected.hvgs.umap$layout )
uncorrected.hvgs.umap$cell = rownames(mbpca.hvgs)
uncorrected.hvgs.umap = merge(uncorrected.hvgs.umap, meta.atlas)

corrected.hvgs.umap = umap(corrected.hvgs, min_dist = 0.7)
corrected.hvgs.umap = as.data.frame(corrected.hvgs.umap$layout)
corrected.hvgs.umap$cell = rownames(corrected.hvgs)
corrected.hvgs.umap = merge(corrected.hvgs.umap, meta.atlas)


# plot
p1 <- ggplot(uncorrected.hvgs.umap, aes(x = X1, y = X2, col = factor(sample) )) + 
  geom_point(size=.5) + 
  ggtitle("Uncorrected ( on HVGs)") + 
  scale_color_Publication() + 
  facet_wrap(~sequencing.batch)
p2 <- ggplot(corrected.hvgs.umap, aes(x = X1, y = X2, col = factor(sample) )) + 
  geom_point(size=.5) + 
  ggtitle("Corrected ( on HVGs)") +
  scale_color_Publication() + 
  facet_wrap(~sequencing.batch)

p <- ggarrange(p1,p2,nrow=2,common.legend = T)
p

p1 <- ggplot(uncorrected.hvgs.umap, aes(x = X1, y = X2, col = factor(sequencing.batch) )) + 
  geom_point(size=.5) + 
  ggtitle("Uncorrected ( on HVGs)") + 
  scale_color_Publication()
p2 <- ggplot(corrected.hvgs.umap, aes(x = X1, y = X2, col = factor(sequencing.batch) )) + 
  geom_point(size=.5) + 
  ggtitle("Corrected ( on HVGs)") +
  scale_color_Publication()

p <- ggarrange(p1,p2,common.legend = T)
p


```

## Seq genes

```{r batch-effect-seq, fig.cap="Batch effect: Seq genes.", fig.height=10, fig.wide=TRUE, warning=FALSE}


# calc PCs
mbpca.seq = multiBatchPCA(sce.cosine[rownames(sce.cosine) %in% rownames(sce.seq),], batch = batchFactor, d = 50)
# batch correct
out = do.call(reducedMNN, mbpca.seq)
corrected.seq = out$corrected

# get UMAP coords
mbpca.seq = do.call(rbind, mbpca.seq)

uncorrected.seq.umap = umap(mbpca.seq, min_dist = 0.7)
uncorrected.seq.umap = as.data.frame( uncorrected.seq.umap$layout )
uncorrected.seq.umap$cell = rownames(mbpca.seq)
uncorrected.seq.umap = merge(uncorrected.seq.umap, meta.atlas)

corrected.seq.umap = umap(corrected.seq, min_dist = 0.7)
corrected.seq.umap = as.data.frame(corrected.seq.umap$layout)
corrected.seq.umap$cell = rownames(corrected.seq)
corrected.seq.umap = merge(corrected.seq.umap, meta.atlas)

# plot
p1 <- ggplot(uncorrected.seq.umap, aes(x = V1, y = V2, col = factor(sample) )) + 
  geom_point(size=.4) + 
  ggtitle("Uncorrected ( on seq genes)") + 
  scale_color_Publication() + 
  facet_wrap(~sequencing.batch)
p2 <- ggplot(corrected.seq.umap, aes(x = V1, y = V2, col = factor(sample) )) + 
  geom_point(size=.4) + 
  ggtitle("Corrected ( on seq genes)") +
  scale_color_Publication() + 
  facet_wrap(~sequencing.batch)

p <- ggarrange(p1,p2,nrow=2,common.legend = T)
p

p1 <- ggplot(uncorrected.seq.umap, aes(x = V1, y = V2, col = factor(sequencing.batch) )) + 
  geom_point(size=.4) + 
  ggtitle("Uncorrected ( on seq genes)") + 
  scale_color_Publication()
p2 <- ggplot(corrected.seq.umap, aes(x = V1, y = V2, col = factor(sequencing.batch) )) + 
  geom_point(size=.4) + 
  ggtitle("Corrected ( on seq genes)") +
  scale_color_Publication()

p <- ggarrange(p1,p2,common.legend = T)
p






```
<!-- # Which sample/batch is good for CT representation -->

<!-- ```{r sample-or-batch-CT-representation, fig.cap="Which samples are good for CT representation.", fig.height=10, fig.wide=TRUE, warning=FALSE} -->

<!-- tab = table(meta.seq.CT$celltype_mapped) -->
<!-- print(tab) -->
<!-- rare.CTs = names(tab)[tab < 100] -->

<!-- tab.atlas = data.frame(table( meta.atlas$sample, meta.atlas$celltype) ) -->
<!-- tab.atlas = tab.atlas[tab.atlas$Var2 %in% rare.CTs,] -->


<!-- tab.atlas = data.frame(table( meta.atlas$sequencing.batch, meta.atlas$celltype) ) -->
<!-- print(tab.atlas) -->



<!-- ``` -->

#Session Info

```{r sessinf}
sessionInfo()
```
