---
title: "Comparison between different mappings"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---

# Load dependencies and source data

```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(igraph)
library(reshape2)
library(knitr)
library(scater)
library(scales)
library(biomaRt)
library(VennDiagram)
library(RColorBrewer)
library(tibble)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(BiocParallel)
library(BiocNeighbors)

ncores = 3
mcparam = MulticoreParam(workers = ncores)
register(mcparam)

#root.dir = "/Users/alsu/Develop/spatial/mouse_embryo/"
root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
figures.dir = paste0(root.dir, "figures/stitching/")
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/visualization_functions.R"))

# load sce files with counts data; clean from cells with 0 area and total # mRNA < user's threshold 
#load_embryo_8.5(threshTotalRNA = 0, filterNullArea = T, filterBigClumps = T, dir = "cluster")

# load my mappings

mapping.pca = readRDS(paste0(root.dir, "data/8_5/celltyping/pca.rds"))
mapping.pca = do.call(c, mapping.pca)
names(mapping.pca) = str_remove(names(mapping.pca) , "embryo1.")
names(mapping.pca) = str_remove(names(mapping.pca) , "embryo2.")
names(mapping.pca) = str_remove(names(mapping.pca) , "embryo3.")

# load scRNA-seq atlas
load_data_atlas(rownames_ensembl = F)
sce.atlas = scater::normalize(sce.atlas)
counts = logcounts(sce.atlas) 
# reduce atlas to only those cells that are among neighbors for seq
K = 25
cells = lapply(mapping.pca, function(x){
  current.cells = x$cells.mapped
  return(current.cells[1:K])
})
cells = do.call( rbind, cells )
cells = cells[order(cells)]
unq.cells = unique(cells)

counts = counts[,colnames(counts) %in% unq.cells]
counts = counts[,order(colnames(counts))]

```

# get average (mean and weighted mean) transcriptome

```{r get-transcriptome}

getCounts = function(cells, weights){
  current.counts = counts[,colnames(counts) %in% cells]
  #current.counts = current.counts[,order(colnames(current.counts) )]
  current.counts = ( current.counts %*% weights )/sum(weights)
  return(current.counts)
}

K = 25
estimated.counts.mean = bplapply(mapping.pca, function(x){
  cells = x$cells.mapped
  cells = cells[1:K]
  idx = order(cells)
  cells = cells[idx]
  weights = rep(1, times = length(cells))
  return(getCounts(cells, weights)) 
}) 
estimated.counts.mean = do.call(cbind, estimated.counts.mean)
colnames(estimated.counts.mean) = names(mapping.pca)
rownames(estimated.counts.mean) = rownames(sce.atlas)
saveRDS(estimated.counts.mean, file = paste0( root.dir, "data/8_5/stitching/pca_K25_mean.rds"))

```



#Session Info

```{r sessinf}
sessionInfo()
```
