---
title: "Comparison between different stitching techniques"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---

# Load dependencies and source data

```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(igraph)
library(reshape2)
library(knitr)
library(scater)
library(scales)
library(biomaRt)
library(VennDiagram)
library(RColorBrewer)
library(tibble)
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(BiocParallel)
library(BiocNeighbors)

ncores = 3
mcparam = MulticoreParam(workers = ncores)
register(mcparam)

root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))

K = 25

# load my mappings
mapping = readRDS(paste0(root.dir, "data/8_5/celltyping/pca.rds"))
mapping = do.call(c, mapping)
names(mapping) = str_remove(names(mapping) , "embryo1.")
names(mapping) = str_remove(names(mapping) , "embryo2.")
names(mapping) = str_remove(names(mapping) , "embryo3.")

# load scRNA-seq atlas
load_data_atlas(rownames_ensembl = F)
sce.atlas = scater::normalize(sce.atlas)
counts.atlas = logcounts(sce.atlas) 

# reduce atlas to only those cells that are among neighbors for seq
cells = lapply(mapping, function(x){
  current.cells = x$cells.mapped
  return(current.cells[1:K])
})
cells = do.call( rbind, cells )
unq.cells = unique(cells)
unq.cells = unq.cells[order(unq.cells)]

counts.atlas = counts.atlas[,colnames(counts.atlas) %in% unq.cells]
counts.atlas = counts.atlas[,order(colnames(counts.atlas))]

```

# Select genes

```{r select-genes}

# 1. seq + sm
load_embryo_8.5(dir = "cluster", smFISH = "lower")
genes.seq_sm = rownames(sce)

# 2. HVGs from reduced atlas
counts.reducedAtlas = readRDS(paste0(root.dir, "data/reducedAtlas/E8_25__E8_5/counts.rds"))
genes.hvg = getHVGs(counts.reducedAtlas, min.mean = 1e-3)

# combine
genes = unique(c(genes.seq_sm, genes.hvg))
counts.atlas = counts.atlas[genes,]


```

# Get stitched: mean

```{r get-mean}

getCounts = function(cells){
  current.counts = counts.atlas[,colnames(counts.atlas) %in% cells]
  current.counts = apply( current.counts , 1, mean)
  return(current.counts)
}
estimated.counts = bplapply(mapping, function(x){
  cells = x$cells.mapped
  cells = cells[1:K]
  return(getCounts(cells)) 
}, BPPARAM = mcparam) 
estimated.counts = do.call(cbind, estimated.counts)
colnames(estimated.counts) = names(mapping)
rownames(estimated.counts) = rownames(counts.atlas)
saveRDS(estimated.counts, file =  paste0( root.dir, "data/8_5/stitching/compareMetrics/nn_", K, "__mean.rds"))

```

# Get stitched: median

```{r get-median}

getCounts = function(cells){
  current.counts = counts.atlas[,colnames(counts.atlas) %in% cells]
  current.counts = apply( current.counts , 1, median)
  return(current.counts)
}
estimated.counts = bplapply(mapping, function(x){
  cells = x$cells.mapped
  cells = cells[1:K]
  return(getCounts(cells)) 
}, BPPARAM = mcparam) 
estimated.counts = do.call(cbind, estimated.counts)
colnames(estimated.counts) = names(mapping)
rownames(estimated.counts) = rownames(counts.atlas)
saveRDS(estimated.counts, file = paste0( root.dir, "data/8_5/stitching/compareMetrics/nn_", K, "__median.rds"))

```

# Get stitched: min

```{r get-min}

getCounts = function(cells){
  current.counts = counts.atlas[,colnames(counts.atlas) %in% cells]
  current.counts = apply( current.counts , 1, min)
  return(current.counts)
}
estimated.counts = bplapply(mapping, function(x){
  cells = x$cells.mapped
  cells = cells[1:K]
  return(getCounts(cells)) 
}, BPPARAM = mcparam) 
estimated.counts = do.call(cbind, estimated.counts)
colnames(estimated.counts) = names(mapping)
rownames(estimated.counts) = rownames(counts.atlas)
saveRDS(estimated.counts, file =  paste0( root.dir, "data/8_5/stitching/compareMetrics/nn_", K, "__min.rds"))

```

# Get stitched: max

```{r get-max}

getCounts = function(cells){
  current.counts = counts.atlas[,colnames(counts.atlas) %in% cells]
  current.counts = apply( current.counts , 1, max)
  return(current.counts)
}
estimated.counts = bplapply(mapping, function(x){
  cells = x$cells.mapped
  cells = cells[1:K]
  return(getCounts(cells)) 
}, BPPARAM = mcparam) 
estimated.counts = do.call(cbind, estimated.counts)
colnames(estimated.counts) = names(mapping)
rownames(estimated.counts) = rownames(counts.atlas)
saveRDS(estimated.counts, file =  paste0( root.dir, "data/8_5/stitching/compareMetrics/nn_", K, "__max.rds"))

```

# Get stitched: 25% quantile 

```{r get-25-quantile}

getCounts = function(cells){
  current.counts = counts.atlas[,colnames(counts.atlas) %in% cells]
  current.counts = apply( current.counts , 1, function(x) quantile(x, .25) )
  return(current.counts)
}
estimated.counts = bplapply(mapping, function(x){
  cells = x$cells.mapped
  cells = cells[1:K]
  return(getCounts(cells)) 
}, BPPARAM = mcparam) 
estimated.counts = do.call(cbind, estimated.counts)
colnames(estimated.counts) = names(mapping)
rownames(estimated.counts) = rownames(counts.atlas)
saveRDS(estimated.counts, file =  paste0( root.dir, "data/8_5/stitching/compareMetrics/nn_", K, "__q25.rds"))

```

# Get stitched: 25% quantile 

```{r get-75-quantile}

getCounts = function(cells){
  current.counts = counts.atlas[,colnames(counts.atlas) %in% cells]
  current.counts = apply( current.counts , 1, function(x) quantile(x, .75) )
  return(current.counts)
}
estimated.counts = bplapply(mapping, function(x){
  cells = x$cells.mapped
  cells = cells[1:K]
  return(getCounts(cells)) 
}, BPPARAM = mcparam) 
estimated.counts = do.call(cbind, estimated.counts)
colnames(estimated.counts) = names(mapping)
rownames(estimated.counts) = rownames(counts.atlas)
saveRDS(estimated.counts, file =  paste0( root.dir, "data/8_5/stitching/compareMetrics/nn_", K, "__q75.rds"))

```

#Session Info

```{r sessinf}
sessionInfo()
```
