---
title: "Small one-time runs for the cluster."
author: "Alsu Missarova"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---



```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(igraph)
library(reshape2)
library(knitr)
library(scater)
library(scales)
library(biomaRt)
library(VennDiagram)
library(RColorBrewer)
library(tibble)
library(ggplot2)
library(tidyverse)
library(irlba)
library(Hmisc)


#root.dir = "/Users/alsu/Develop/spatial/mouse_embryo/"
root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))

anno = read.table(paste0( root.dir, "data/8_5/geneInfo/stat.tab"), header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")
CT = read.table(paste0( root.dir, "data/8_5/celltyping/CT__freeze__21042020.tab"), header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")

# load stitching
counts.stitched = readRDS(paste0(root.dir, "data/8_5/stitching/pca_K10_mean.rds"))

genes.to.check = c("4930556M19Rik","A230057D06Rik","Adat3","Btbd8","Ccl27a","D130017N08Rik","Dancr","Dohh","Gm15853","Gm16381","Gm16701","Gm2464","Gm2696","Gm3055","Itgam","Jakmip1","Map2k7","Nudt8","Olfr912","Pcdha11","Raver1","Rnf26","Sept2","Spata22","Srp54a","St6galnac2","Sumo3","U2af1l4","Zfp935")
# load stitching
counts.stitched = readRDS(paste0(root.dir, "data/8_5/stitching/pca_K10_mean.rds"))
counts.stitched.dubious = counts.stitched[rownames(counts.stitched) %in% genes.to.check,]
saveRDS(counts.stitched.dubious, file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__toCheck.rds"))



```



#Session Info

```{r sessinf}
sessionInfo()
```
