---
title: "Assessment of the  stitching quality: seqFISH genes"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---


# Load dependencies and source data

```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(igraph)
library(reshape2)
library(knitr)
library(scater)
library(scales)
library(biomaRt)
library(tibble)
library(tidyverse)

ncores = 1

#root.dir = "/Users/alsu/Develop/spatial/mouse_embryo/"
root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))

# load sce files with counts data; clean from cells with 0 area and total # mRNA < user's threshold 
load_embryo_8.5(filterNullArea = TRUE, threshTotalRNA = 20, threshTotalGenes = 10, filterBigClumps = TRUE, filterEdgeZ = TRUE,
                           dir = "cluster", smFISH = "lower")
genes.seq_sm = rownames(sce)

# load sce files with counts data; clean from cells with 0 area and total # mRNA < user's threshold 
load_embryo_8.5(filterNullArea = TRUE, threshTotalRNA = 20, threshTotalGenes = 10, filterBigClumps = TRUE, filterEdgeZ = TRUE,
                           dir = "cluster", smFISH = "none")
meta.seq = data.frame(meta)
counts.seq = assay(sce, "logcounts.area")
genes.seq = rownames(sce)
genes.sm = setdiff(genes.seq_sm, genes.seq)

# load stitching
counts.stitched = readRDS(paste0(root.dir, "data/8_5/stitching/pca_K10_mean.rds"))
genes = rownames(counts.stitched)

# pull CT
CT = read.table(paste0( root.dir, "data/8_5/celltyping/CT__freeze__21042020.tab"), header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")

```


# Seq-FISH genes


```{r get-stitch-seq}
# 
counts.stitched.seq = counts.stitched[genes.seq,]
saveRDS(counts.stitched.seq, file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__seq.rds"))

```

# smFISH genes


```{r get-stitch-sm}
# 
counts.stitched.sm = counts.stitched[genes.sm,]
saveRDS(counts.stitched.sm, file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__sm.rds"))

```


# Markers

```{r get-stitch-markers}
# 
markers = read.table(paste0( root.dir, "data/QC_stitching/CT_markers.tab"), header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")
unq.gene = markers$gene

counts.stitched.markers = counts.stitched[unq.gene,]
saveRDS(counts.stitched.markers, file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__markers.rds"))

```


# Custom datasets

## Nowotschin et al., 2019

```{r custom-nowotschin}
# 
df = read.table(paste0( root.dir, "data/QC_stitching/Nowotschin_et_al__2019.tab"), header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")
unq.gene = unique(df$Gene)
unq.gene = intersect(rownames(counts.stitched), unq.gene)
counts.stitched.custom = counts.stitched[unq.gene,]
saveRDS(counts.stitched.custom, file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__Nowotschin.rds"))


```


## Ibarra-Sorria et al., 2018

```{r custom-ibarra_sorria}
# 
df = read.table(paste0( root.dir, "data/QC_stitching/Ibarra_Sorria_et_al_2018.tab"), header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")
unq.gene = unique(df$Gene)
unq.gene = intersect(rownames(counts.stitched), unq.gene)
counts.stitched.custom = counts.stitched[unq.gene,]
saveRDS(counts.stitched.custom, file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__Ibarra_Sorria.rds"))

```

# HVGs

## All 

```{r hvgs-all}
# 
HVGs = getHVGs(counts.stitched, min.mean = 1e-3, gene_df = genes)
counts.stitched.hvgs = counts.stitched[HVGs,]
saveRDS(counts.stitched.hvgs , file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__hvgs.rds"))

```

## Brain and spinal cord

```{r hvgs-brain-spinal}
# 
idx = which( CT$CT %in% c("Forebrain/Midbrain/Hindbrain", "Spinal cord") )
HVGs = getHVGs(counts.stitched[,CT$uniqueID[idx]], min.mean = 1e-3, gene_df = genes)
counts.stitched.hvgs = counts.stitched[HVGs,]
saveRDS(counts.stitched.hvgs , file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__brain_spinalCord.rds"))

```

## Gut, Def. endoderm and Visceral endoderm

```{r hvgs-gut-endoderm}
# 
idx = which( CT$CT %in% c("Gut", "Def. endoderm", "Visceral endoderm") )
HVGs = getHVGs(counts.stitched[,CT$uniqueID[idx]], min.mean = 1e-3, gene_df = genes)
counts.stitched.hvgs = counts.stitched[HVGs,]
saveRDS(counts.stitched.hvgs , file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__gut_endoderm.rds"))

```

## Gut

```{r hvgs-gut-endoderm}
# 
idx = which( CT$CT %in% c("Gut") )
HVGs = getHVGs(counts.stitched[,CT$uniqueID[idx]], min.mean = 1e-3, gene_df = genes)
counts.stitched.hvgs = counts.stitched[HVGs,]
saveRDS(counts.stitched.hvgs , file = paste0( root.dir, "data/8_5/stitching/pca_K10_mean__gut.rds"))

```

#Session Info

```{r sessinf}
sessionInfo()
```
