---
title: "Spatial mouse - cell cycle scoring"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
    titlecaps: true
---

```{r load-atlas, message = FALSE, warning = FALSE}

library(Matrix)
library(scran)
library(dplyr)
library(biomaRt)
library(scales)
library(knitr)
library(reshape2)
library(Seurat)
knitr::opts_chunk$set(cache=TRUE, warning = FALSE, 
                     message = FALSE, cache.lazy = FALSE)

root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))

load_embryo_8.5(version = "old_filtered", dir = "cluster")
counts.seq = assay(sce, "logcounts.area")

# only work with embryo1 and embryo2 and mesenchyme
idx = meta$embryo %in% c("embryo1", "embryo2") & meta$z %in% c(2, 5)
meta = meta[idx,]

# load stitching 
counts = readRDS(paste0( root.dir, "data/8_5/stitching/pca_K10_mean.rds") )

# delete after scrupt is re-run (colnames should match)
id = intersect( colnames(counts) , colnames(counts.seq) )
counts = counts[,colnames(counts) %in% id]
meta = meta[meta$uniqueID %in% id,]

# order all
meta = meta[order(meta$uniqueID),]
counts = counts[,order(colnames(counts))]

genes = rownames(counts)
rownames(counts) = toupper( rownames(counts) ) 
colnames(counts) = meta$uniqueID


```

# Cell-cycle scoring

```{r cc-scoring}

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

countsSeurat <- CreateSeuratObject(counts = counts)
countsSeurat <- NormalizeData(countsSeurat)
countsSeurat <- FindVariableFeatures(countsSeurat, selection.method = "vst")
countsSeurat <- ScaleData(countsSeurat, features = rownames(countsSeurat))
  
ccSeurat <- CellCycleScoring(countsSeurat, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE) 
meta$cellCycle = ccSeurat$Phase

write.table(meta, file = paste0( root.dir, "data/8_5/meta__w_cc.tab"), row.names = F, col.names = T, quote = F, sep = "\t")

```

# Session Info
```{r sessinf}
sessionInfo()
```

