---
title: "Comparison between different mappings"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---

# Load dependencies and source data

```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(igraph)
library(reshape2)
library(knitr)
library(scater)
library(scales)
library(biomaRt)
library(VennDiagram)
library(RColorBrewer)
library(tibble)
library(ggplot2)
library(tidyverse)
library(ggpubr)

#root.dir = "/Users/alsu/Develop/spatial/mouse_embryo/"
root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
figures.dir = paste0(root.dir, "figures/stitching/")
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/visualization_functions.R"))

# load sce files with counts data; clean from cells with 0 area and total # mRNA < user's threshold 
load_embryo_8.5(threshTotalRNA = 0, filterNullArea = T, filterBigClumps = T, dir = "cluster")

# load my mappings
mapping.marker = readRDS(paste0(root.dir, "data/8_5/celltyping/markers.rds"))
mapping.marker = do.call(c, mapping.marker)
names(mapping.marker) = str_remove(names(mapping.marker) , "embryo1.")
names(mapping.marker) = str_remove(names(mapping.marker) , "embryo2.")
names(mapping.marker) = str_remove(names(mapping.marker) , "embryo3.")

# load meta-atlas
meta.atlas = read.table("/nfs/research1/marioni/alsu/FetalAlcoholSyndrome/atlas_Jonny/data/meta.tab", header = TRUE, sep = "\t", stringsAsFactors = FALSE, comment.char = "$")

```

# Pull sample, stage, theiler

```{r assign-mode}


addInfo = function(mapping){
  addInfo.perCell = lapply(mapping, function(x){
    cells = x$cells.mapped
    x$samples = sapply(cells, function(y) meta.atlas$sample[meta.atlas$cell == y])
    x$stages = sapply(cells, function(y) meta.atlas$stage[meta.atlas$cell == y])
    x$theiler = sapply(cells, function(y) meta.atlas$theiler[meta.atlas$cell == y])
    return(x)
  })
  return(addInfo.perCell)
}

mapping.marker.info= addInfo(mapping.marker)
saveRDS(mapping.marker.info, file = paste0( root.dir, "data/8_5/celltyping/marker_wInfo.rds"))

```



#Session Info

```{r sessinf}
sessionInfo()
```
