---
title: "Mapping seqFISH data (by logcounts.libsize) onto scRNA-seq"
output:
  BiocStyle::html_document:
    code_folding: hide
    number_sections: yes
    toc: yes  
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: true
    theme: united
---

# Load dependencies and source data

```{r load_data, message=FALSE}

library(Matrix)
library(scran)
library(BiocParallel)
library(BiocNeighbors)
ncores = 6
mcparam = MulticoreParam(workers = ncores)
register(mcparam)
library(igraph)
library(reshape2)
library(knitr)
library(scater)
library(scales)
library(biomaRt)

#root.dir = "/Users/alsu/Develop/spatial/mouse_embryo/"
root.dir = "/nfs/research1/marioni/alsu/spatial/mouse_embryo/"
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/core_functions.R"))
source(paste0(root.dir, "amScripts_mouseEmbryoFISH/visualization_functions.R"))

# load sce files with counts data; clean from cells with 0 area and total # mRNA < user's threshold 
load_embryo_8.5(threshTotalRNA = 0, filterNullArea = T, filterBigClumps = T, dir = "cluster")

# work only with the embryo_1 for now
idx = meta$embryo == "embryo_1"
meta = meta[idx,]
sce = sce[,idx]

# discard Xist 
idx = setdiff(1:dim(sce)[1], which(rownames(sce) %in% c("Xist")) )
sce = sce[idx,]
  
# load scRNA-seq atlas
load_data_atlas(rownames_ensembl = F)
sce.atlas = scater::normalize(sce.atlas)
meta.atlas$celltype[meta.atlas$doublet] = "Doublet"
meta.atlas$celltype[meta.atlas$stripped] = "Stripped"

# discard doublets and stripped for the atlas - we don't want to map to them
idx = !meta.atlas$celltype %in% c("Doublet", "Stripped")
meta.atlas = meta.atlas[idx,]
sce.atlas = sce.atlas[,idx]

# keep only those genes that are in seqFISH (excluding Xist and Cavin3)
idx = rownames(sce.atlas) %in% rownames(sce)
sce.atlas = sce.atlas[idx,]

# get the same order of rows for sce and sce.atlas
sce = sce[order(rownames(sce)),]
sce.atlas = sce.atlas[order(rownames(sce.atlas)),]

```

This script performs KNN based mapping: seqFISH onto Jonny's atlas.

# Mapping 

## Area

```{r mapping-area}

# get z-counts for seq
counts = assay(sce, "logcounts.area")
z.counts = apply(counts, 1, function(x){
  out = scale(x)
  out[is.na(out)] <- 0
  return(out)
})
rownames(z.counts) = colnames(counts)
z.counts = z.counts[,order(colnames(z.counts))]

# get z-counts for atlas
counts.atlas = assay(sce.atlas, "logcounts")
z.counts.atlas = apply(counts.atlas, 1, function(x){
  out = scale(x)
  out[is.na(out)] <- 0
  return(out)
})
rownames(z.counts.atlas) = colnames(counts.atlas)
z.counts.atlas = z.counts.atlas[,order(colnames(z.counts.atlas))]

# get knn-graph
k.neigh = 50
knns = queryKNN(z.counts.atlas, z.counts, k = k.neigh, get.index = TRUE, 
                get.distance = TRUE, BPPARAM=mcparam)

# get stat
k.mapped = t(apply(knns$index, 1, function(x) meta.atlas$cell[x]))
celltypes = t(apply(k.mapped, 1, function(x) meta.atlas$celltype[match(x, meta.atlas$cell)]))
celltype.mapped = apply(celltypes, 1, function(x) getmode(x, 1:length(x)))
celltype.mapped.fraction = apply(celltypes, 1, function(x) mean(x == getmode(x, 1:length(x))))
celltype.mapped.match = t(apply(celltypes, 1, function(x) match(x, getmode(x, 1:length(x)))))
knns$distance = knns$distance * celltype.mapped.match
distance.mapped = rowMeans(knns$distance, na.rm = TRUE)
  
mappings.area = lapply(1:dim(knns$index)[1], function(x){
  out = list(cells.mapped = k.mapped[x,],
             celltypes.mapped = celltypes[x,],
             celltype.mode = celltype.mapped[x],
             celltype.mode.fraction = celltype.mapped.fraction[x],
             distances.mapped = knns$distance[x,],
             distance.mean = distance.mapped[x])
  return(out)
})
names(mappings.area) = meta$uniqueID
saveRDS(mappings.area, file = paste0( root.dir, "data/8_5/mapping/logcounts_area__knn__embryo_1.rds"))

```

## Libsize

```{r mapping-libsize}

# get z-counts for seq
counts.area = assay(sce, "logcounts.libsize")
z.counts = apply(counts, 1, function(x){
  out = scale(x)
  out[is.na(out)] <- 0
  return(out)
})
rownames(z.counts) = colnames(counts)
z.counts = z.counts[,order(colnames(z.counts))]

# get z-counts for atlas
counts.atlas = assay(sce.atlas, "logcounts")
z.counts.atlas = apply(counts.atlas, 1, function(x){
  out = scale(x)
  out[is.na(out)] <- 0
  return(out)
})
rownames(z.counts.atlas) = colnames(counts.atlas)
z.counts.atlas = z.counts.atlas[,order(colnames(z.counts.atlas))]

# get knn-graph
k.neigh = 50
knns = queryKNN(z.counts.atlas, z.counts, k = k.neigh, get.index = TRUE, 
                get.distance = TRUE, BPPARAM=mcparam)

# get stat
k.mapped = t(apply(knns$index, 1, function(x) meta.atlas$cell[x]))
celltypes = t(apply(k.mapped, 1, function(x) meta.atlas$celltype[match(x, meta.atlas$cell)]))
celltype.mapped = apply(celltypes, 1, function(x) getmode(x, 1:length(x)))
celltype.mapped.fraction = apply(celltypes, 1, function(x) mean(x == getmode(x, 1:length(x))))
celltype.mapped.match = t(apply(celltypes, 1, function(x) match(x, getmode(x, 1:length(x)))))
knns$distance = knns$distance * celltype.mapped.match
distance.mapped = rowMeans(knns$distance, na.rm = TRUE)
  
mappings.libsize = lapply(1:dim(knns$index)[1], function(x){
  out = list(cells.mapped = k.mapped[x,],
             celltypes.mapped = celltypes[x,],
             celltype.mode = celltype.mapped[x],
             celltype.mode.fraction = celltype.mapped.fraction[x],
             distances.mapped = knns$distance[x,],
             distance.mean = distance.mapped[x])
  return(out)
})
names(mappings.libsize) = meta$uniqueID
saveRDS(mappings.libsize, file = paste0( root.dir, "data/8_5/mapping/logcounts_libsize__knn__embryo_1.rds"))

```





#Session Info
```{r sessinf}
sessionInfo()
```
